### ISSUE TITLE
Weather Shortcut - Change Text Colour

### ISSUE THREAD

**Issue by Just-Insane** [thewaytozion/widgets#3]
Hello,

I am looking to change the font colour in the Weather shortcut from this repo. From what I can tell, the font is set to #ffffff, which should be white, however on my screen it looks more gray then white.

Is there another place where the font colour is set?

Thanks

**Comment by thewaytozion** [comment]
Hello & thanks for input. 

The issue here is, that I'm modifying the wallpaper itself. Save the image and set it as a wallpaper. 

You can try it manually. Take a dark image and place a small ffffff rectangle on it. Save it and set it manually as a wallpaper. The rectangle will not be white, Apple will set another dark layer above the wallpaper in order to make clock (layer) more readable. 

You can not change it as of now.

**Comment by Just-Insane** [comment]
Ah, that makes sense. Thank you.
